### ISSUE TITLE
lottie-player.js to ES5

### ISSUE THREAD

**Issue by vasilis-exo** [LottieFiles/lottie-player#10]
Hi,

Is there any way to compile the lottie-player.js to ES5 ? 
I have an old project and I want to implement this library in order to have this functionality.

How I can achieve it?

Thank you in advance

**Comment by littlee** [comment]
@vasilis-exo have you solve your problem ?

**Comment by vasilis-exo** [comment]
@littlee yeap! I solved it. Thanks!
