### ISSUE TITLE
Latest version of lottie-player.js conflict with scrollTrigger pinning

### ISSUE THREAD

**Issue by lamtruong606** [LottieFiles/lottie-player#102]
This is my first time reporting an issue so I'm not really sure if this is the right place for that. Sorry in advance if I'm posting this in a wrong place.

So I have experienced an issue with the @latest version of lottie-player cdn link on my website. 
It somehow makes the <lottie-player> tag completely disapear when using in a section with ScrollTrigger and set pin: true; 
But the problem was fixed when I change the cdn form @latest version to @1.1.1

This is something I just want to let you guys know in order to avoid any futher issues.

**Comment by samuelOsborne** [comment]
@lamtruong606 Hi! Thanks for bringing this up. Is it ScrollTrigger from GreenSock that you're using ?

**Comment by samuelOsborne** [comment]
Hi @Azolia-Design, I did try and find a fix but to no avail. However I've added this scroll pinning feature to the to-do list for lottie-interactivity, if it works using the v1.1.1 in the meantime, please use that version.
