### ISSUE TITLE
Safari 15.0 SVG sizing is off (also affecting https://lottiefiles.com)

### ISSUE THREAD

**Issue by jorgelainfiesta** [LottieFiles/lottie-player#103]
Hi,

I noticed today that Safari 15.0 seems to be ignoring the fixed pixel attribute `width=` and `height=` in the SVG within the lotty player, and only using the percentage from the inline style which yield unexpected sizes. 

How it looks in Safari 15.0:
![Screenshot 2021-09-28 at 16 07 57](https://user-images.githubusercontent.com/4451393/135104036-b471fb74-dad5-4c69-b43d-838d7d76c32d.png)
![Screenshot 2021-09-28 at 16 07 53](https://user-images.githubusercontent.com/4451393/135104048-8df8390e-273f-465c-a54c-38af5c570bcb.png)
)

This is how it looks normally (in Chrome, or Firefox):
![Screenshot 2021-09-28 at 16 09 18](https://user-images.githubusercontent.com/4451393/135103951-d3a0ccbd-25af-4d33-8456-bc3a982082de.png)
![Screenshot 2021-09-28 at 16 09 21](https://user-images.githubusercontent.com/4451393/135103964-0769e0bc-a2c1-42b7-807d-da765beb9322.png)

I've been trying to find out what changed in Safari to cause this, but haven't found many resources. 

Thanks,
Jorge L

**Comment by jorgelainfiesta** [comment]
Upon further investigation, I noticed that this only happens if the parent container doesn't have an explicit width. I was able to fix my issue by setting a fixed size to my flexbox column. Thanks!

**Comment by karamalie** [comment]
working to fix this on lottiefiles.com @jorgelainfiesta . The issue can be set by setting the height and width in the <lottieplayer> element and removing the parents width and height.

**Comment by karamalie** [comment]
@JoshuaRobertson could you drop me the Lottie file you re using so i can replicate the issue

**Comment by kallelat** [comment]
@karamalie I can also try to make an example next week (if having enough time)...

@JoshuaRobertson I think I got semiworking version by adding an extra div wrapper around lottie-player - it doesn't have any special css, but a plain dummy div - but in some magical way I haven't seen that much issues anymore.

**Comment by JoshuaRobertson** [comment]
@karamalie thanks for getting back to me. I've attached one of the files I'm using (zipped for upload ease). Here's my current solution too with a defined `height` which seems to be the most important attribute to guarantee it displays. On smaller viewports I can then update the `height` but hopefully there's an easier way.

I'm using the animations on [this site](https://creditfusion.co.uk/) and if you view it in Safari and remove the `height` from the `lottie-wrapper` you should be able to see the issue.

**Current solution**

```
<div class="lottie-wrapper">
  <lottie-player
    autoplay
    loop
    mode="normal"
    src="{{ asset('/lottie/home/intro.json') }}"
    class="lottie-default"
  />
</div>
```

```
.lottie-wrapper {
  width: 100%;
  height: 18rem;
}

.lottie-default {
  width: 100%;
  height: 100%;
}
```

[intro.json.zip](https://github.com/LottieFiles/lottie-player/files/7362801/intro.json.zip)

Thanks in advance.

**Comment by karamalie** [comment]
Setting a height to the container should do the trick @JoshuaRobertson. Here's more info about the issue. It's more of an svg working differently with safari vs chrome [Click here ](https://stackoverflow.com/questions/26091989/svg-viewbox-height-issue-on-ios-safari#:~:text=5%20Answers&text=The%20problem%20is%20that%20you,it%20in%20the%20other%20direction.)
