### ISSUE TITLE
Lottie web player does not seem to work in IE

### ISSUE THREAD

**Issue by TiwariShubham** [LottieFiles/lottie-player#11]
**Tell us about your environment**
Windows 10, 64 Bit

**Browser and Browser Version**: IE-11

**What did you do? Please explain the steps you took before you encountered the problem.** 

I injected the lottie web player in the HTML, with the below snippet:

`<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player  src="https://assets9.lottiefiles.com/datafiles/MUp3wlMDGtoK5FK/data.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay >
</lottie-player>`

**What did you expect to happen?**

It should have shown animation like this, which works in Chrome, Firefox and Safari

<img width="1364" alt="Screen Shot 2019-10-25 at 3 34 09 pm" src="https://user-images.githubusercontent.com/8822599/67729487-6672d580-fa45-11e9-8487-f7fe40f2a8f0.png">

**What actually happened? Please include as much relevant detail as possible.**

It showed like this in IE-11

<img width="1377" alt="Screen Shot 2019-10-25 at 3 33 51 pm" src="https://user-images.githubusercontent.com/8822599/67729509-74285b00-fa45-11e9-90f0-7dabb2ea56cd.png">

**Comment by ibrahimnamdarmobven** [comment]
same here

**Comment by ibrahimnamdarmobven** [comment]
I ended up using this for IE11 support: 
https://github.com/airbnb/lottie-web

**Comment by TiwariShubham** [comment]
yeah but you need to specify ID for every container for it, hence I was trying to figure it out if they can make this work in IE, would get rid of the ID contigency.

**Comment by Yejielw** [comment]
IE doesnt support Custom Web components, you would need to add a polyfill
check this from more info https://www.npmjs.com/package/@webcomponents/webcomponentsjs#how-to-use

**Comment by karamalie** [comment]
The player is a web component. Please add polyfills to your project for support on older browsers. Closing issue
