### ISSUE TITLE
Lottie player shows error, works just when clicking on "play"

### ISSUE THREAD

**Issue by adinu** [LottieFiles/lottie-player#110]
Hi,

i have this strange error with this specfiic lottie.json
https://anima-uploads.s3.amazonaws.com/projects/616d72eb2f71a8446d209785/files/b2.json

https://projects.animaapp.com/p/02Ghvpw/ulBYJKx/player-off/prototype?platform=xd

it seems to be showing error, until clicking on play button. maybe someone can explain to me the reason for that? we are using the latest lottie player in the site (https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js)

**Comment by karamalie** [comment]
hi @adinu this is not an issue with the player. had a look at the JSON file and it looks like a bug during export from After Effects. are you using the latest version of the After Effects plugin?
