### ISSUE TITLE
Lottie not working on deploy.

### ISSUE THREAD

**Issue by EliseiNicolae** [LottieFiles/lottie-player#115]
I add the Lottie package on my angular project and works fine on **localhost:4200**.

But, when I deploy to netlify, it doesn't work.
I have a warning on my console:
"Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'."

![image](https://user-images.githubusercontent.com/43387542/140915504-d336b5a2-064e-4a09-81cf-29d1f8d43f77.png)

Any ideas on how can I solve the issue?

**Comment by karamalie** [comment]
the warning should be of no consequence. are there any other red errors that show up in the console? Do note that the player has to be imported as a client side only library on angularJS. server side rendering will not work

**Comment by EliseiNicolae** [comment]
Not red errors.

I'm using @angular/cli": "~12.2.11

For implementation I do like that:
1. `npm install --save @lottiefiles/lottie-player`
2. Update app.module.ts
![image](https://user-images.githubusercontent.com/43387542/140921675-d1a6e3e4-91af-4c09-99dc-de36e94c0644.png)
3. Add HTML tag on my component:
```
    <lottie-player
            autoplay
            loop
            mode="normal"
            src="https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json"
            style="width: 320px"
    >
    </lottie-player>
```

**Comment by karamalie** [comment]
have you imported the lottie-player? 2nd step should be importing the player in. cant see a player import in the screenshot

**Comment by EliseiNicolae** [comment]
Do you mean to import `import "@lottiefiles/lottie-player";` in my `.ts` component?

**Comment by karamalie** [comment]
heres a working example i just built https://codesandbox.io/s/gifted-morse-2tl58?file=/src/app/app.module.ts
1 - add the lottie player script to index.html
2- enable custom elements for the angular project (have a look at app.module.ts)
3 - add the player to component.html

**Comment by karamalie** [comment]
angular requires you to enable custom elements before using web components. 
angular also requires you to import scripts differently

**Comment by EliseiNicolae** [comment]
Thanks, @karamalie, now working fine.

So the problem arose because I had installed lottie-player with` npm install --save @lottiefiles/lottie-player` instead of importing the <script> in index.html of an Angular project.

(`<script src="https://unpkg.com/@lottiefiles/lottie-player@1.4.4/dist/lottie-player.js"></script>`)

**Comment by karamalie** [comment]
No problem. Happy to help!
