### ISSUE TITLE
Add translation on Aria-label for accessibility

### ISSUE THREAD

**Issue by nicolasambroise** [LottieFiles/lottie-player#120]
Hello, I want to use lottie-player but I find an issue when I use Voice-over feature in an other language than English.
They are no translation for aria-label on the buttons of the Lottie player controller bar.
 
For the moment, I put directly the French translation in "lottie-player.ts" but it will be nice if we could add a lang attribute on the <lottie-player> tag. With this new attribute, you could easily include lottie-player in multi-language websites.

**Comment by samuelOsborne** [comment]
Hi @nicolasambroise , thank you for your suggestion, I'm looking in to getting this added.

**Comment by samuelOsborne** [comment]
Hi @nicolasambroise I've added the lang tags to the buttons and it's been merged :-)

**Comment by nicolasambroise** [comment]
Thanks for the modification, but not exactly what I expected as the lang attribute is only needed on the parent element.
On top of that, I made 2 pull requests in order of improving accessibility.
- #127 
- #128 
I will continue to contribute with these 2 pull requests in parallel with my development.
