### ISSUE TITLE
Latest version 1.5.2 is missing the tgs-player.js file

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [LottieFiles/lottie-player#129]
As you can see [here](https://unpkg.com/browse/@lottiefiles/lottie-player@1.5.2/dist/), the `tgs-player.js` file is missing in the latest version. I noticed as I was using the latest version and suddenly my animations failed to load.

Could you check it please?

Thank you!

**Comment by karamalie** [comment]
hi @rodrigoalcarazdelaosa thanks for pointing it out. pushing a release asap

**Comment by karamalie** [comment]
updated @rodrigoalcarazdelaosa ,please check and update issue. thank you

**Comment by rodrigoalcarazdelaosa** [comment]
Solved! Thank you very much for the swift response!
