### ISSUE TITLE
outdated version for shx dependency

### ISSUE THREAD

**Issue by ibrayo1** [LottieFiles/lottie-player#132]
The current version of shx in the package.json file is 0.3.3 and consumes an outdated version of shelljs, which has security vulnerabilities, and should get updated to 0.3.4. Please see below references.

**References**
- [Github Commit](https://github.com/shelljs/shelljs/commit/003a39d652039f2171aca66770d1d7326dd3b216)
- [Github Issue](https://github.com/shelljs/shelljs/issues/1058)
- [Github PR](https://github.com/shelljs/shelljs/pull/1060)

**Comment by restfulhead** [comment]
Yes, and it should be moved to dev dependencies https://github.com/LottieFiles/lottie-player/issues/139

**Comment by samuelOsborne** [comment]
Hi. @ibrayo1  and @restfulhead, this will be included in our next release, I'll ping you when it's out! 

@restfulhead Im going to close your issue, as its a duplicate of this one.

**Comment by samuelOsborne** [comment]
Fix is in PR: #138

**Comment by restfulhead** [comment]
Thanks for the prompt fix. Could this be released to NPM?

**Comment by samuelOsborne** [comment]
Hey folks, this is up on npm.
