### ISSUE TITLE
Style animation elements using CSS

### ISSUE THREAD

**Issue by foguetes** [LottieFiles/lottie-player#14]
Does this player support styling objects the same way as lottie-web?

https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

If so, could you provide a simple example?

**Comment by karamalie** [comment]
You can add classnames to layers via After Effects. Those layers when rendered will have the classnames on the html elements.

You should be able to then do something like

var layer = document.querySelector('layer-id-here');

once you have a handle on the element you can add css via js to that element.
