### ISSUE TITLE
vscode viewer

### ISSUE THREAD

**Issue by farfromrefug** [LottieFiles/lottie-player#140]
Could you make the vscode extension open source?
I am in the need of a better "toolbar" for the lottie-player showing the frame and allowing me to go frame by frame.
The vscode viewer is pretty great!

Thanks

**Comment by samuelOsborne** [comment]
Hi @farfromrefug This isn't currently on our roadmap, but we'll look in to this going ahead. Cheers.

**Comment by farfromrefug** [comment]
@samuelOsborne thanks for answering i actually gound out the vscode was simply using the lottie svelte code which is ope source. So all good!
