### ISSUE TITLE
Error in console: lottie-player.esm.js?a717:172 GET http://localhost:8080/undefined 404 (Not Found)

### ISSUE THREAD

**Issue by jarooda** [LottieFiles/lottie-player#142]
Hello, i am using nuxt, and implement lottie-player like this

```html
<lottie-player
    autoplay
    loop
    class="lottie-animation"
    :src="JSON.stringify(lottieAnimation)"
    speed="1"
    debug
/>
```

the animation play successfully and there is no error visible in browser, but if I look at console, there is 6 error like this

<img width="1352" alt="Screen Shot 2022-02-04 at 11 15 11" src="https://user-images.githubusercontent.com/71919479/152470843-79d1d2b6-413b-44f6-8b9d-2d221d7aaf86.png">

how can I get rid the console error? thankyou

**Comment by samuelOsborne** [comment]
@jarooda This may be due to the component trying to load animations before it is mounted, and the src prop being undefined. Have you tried loading animations pragmatically in the ```mounted()``` hook?

https://github.com/LottieFiles/lottie-player#lottie-player-1

**Comment by jarooda** [comment]
cool, this is working, thankyou!
