### ISSUE TITLE
How can I use lottie-player in typescript?

### ISSUE THREAD

**Issue by Jycjmf** [LottieFiles/lottie-player#146]
Hi , I am trying to use lottie-player in Vue 3 with Typescript .
In the template , I add the code below:
```
<template>      
      <lottie-player mode="normal" />
</template>
```
In the script , I add another code below:
```
<script setup lang="ts">
      import { LottiePlayer } from "@lottiefiles/lottie-player";
      import successAnimation from "../assets/tick_animation.json";

      onMounted(() => {
              const player = document.querySelector("lottie-player") as LottiePlayer;
              player?.load(successAnimation);
              player?.play();
      });
</script>
```
But it throw an error:
`Uncaught (in promise) TypeError: Class constructor LottiePlayer cannot be invoked without 'new'`

My question is how can I use lottie-player in Ts , Thanks .

**Comment by samuelOsborne** [comment]
Hi @Jycjmf, you need to change your import from  

```
import { LottiePlayer } from "@lottiefiles/lottie-player"
```

to

```
import "@lottiefiles/lottie-player";
```

I've also updated the readme, you need to listen for the "rendered" event to load animations pragmatically, your code should look like this:

```
onMounted(() => {
    const player = document.querySelector("lottie-player") as LottiePlayer;
    console.log(player);
    player?.addEventListener("rendered", (e) => {
      player?.load(
        "successAnimation"
      );
      player.play();
  });
});
```

**Comment by Jycjmf** [comment]
> Hi @Jycjmf, you need to change your import from
> 
> ```
> import { LottiePlayer } from "@lottiefiles/lottie-player"
> ```
> 
> to
> 
> ```
> import "@lottiefiles/lottie-player";
> ```
> 
> I've also updated the readme, you need to listen for the "rendered" event to load animations pragmatically, your code should look like this:
> 
> ```
> onMounted(() => {
>     const player = document.querySelector("lottie-player") as LottiePlayer;
>     console.log(player);
>     player?.addEventListener("rendered", (e) => {
>       player?.load(
>         "successAnimation"
>       );
>       player.play();
>   });
> });
> ```

Ok , thanks bro!
