### ISSUE TITLE
Lottie export not working properly (Need help with export settings)

### ISSUE THREAD

**Issue by rdcoder33** [LottieFiles/lottie-player#148]
Hey there,
I tried to export this animation as a JSON but the result is not how it suppose to be

AE File:
[character_animation.aep.zip](https://github.com/bodymovin/bodymovin-extension/files/8148076/character_animation.aep.zip)
.

Exported Lottie file:
https://lottiefiles.com/share/z8eumozd

Did I need to make some changes in the export setting or what?

**Comment by samuelOsborne** [comment]
Hi @rdcoder33 I can't see the animation you shared on lottiefiles, is this still a problem? 
Also, this question might be better suited for the discord where other people can help you with this, you can join it here:

http://lottiefiles.com/discord
