### ISSUE TITLE
Lottie Interactivity with custom element on Editor X/Wix

### ISSUE THREAD

**Issue by joeisdead** [LottieFiles/lottie-player#150]
Hi, I'm designing a website using Editor X (Wix.)

I'm looking to sync my lottie animation with scroll, so that the svg path traces as the user scrolls.

I have a custom element setup on my page that plays the animation, however I'm struggling to implement the interactivity 'sync with scroll' part.

Could someone help me with this?

**Comment by karamalie** [comment]
could we have some sample code to look at please @joeisdead

**Comment by joeisdead** [comment]
The custom element is set up with this source:
<img width="266" alt="Screenshot 2022-03-22 at 10 14 02" src="https://user-images.githubusercontent.com/17277887/159458107-ae529a44-bc71-41f0-afbd-f96cefa942c0.png">
 
and these attributes: 
<img width="247" alt="Screenshot 2022-03-22 at 10 13 51" src="https://user-images.githubusercontent.com/17277887/159458196-ffe3d382-8ce7-4477-84ec-61572729ae3e.png">

I have both lottie-interactivity and lottie-player packages installed on the npm section of the dev toolbar. This is the code that I have written in the 'Home' page code tab (not completely sure it's in the right place)

```
<script>
import '@lottiefiles/lottie-player';
import '@lottiefiles/lottie-interactivity';
import { create } from '@lottiefiles/lottie-interactivity';


LottieInteractivity.create({
    player: '#firstLottie',
    mode: 'scroll',
    actions: [
        {
            visibility: [0, 1.0],
            type: 'seek',
            frames: [0, 73],
        },
    ]
});
</script>
```

**Comment by samuelOsborne** [comment]
@joeisdead Do you have any errors? Or is it just not animating? 

Seeing as you import just create from LottieInteractivity, have you tried:

```
create({
    player: '#firstLottie',
    mode: 'scroll',
    actions: [
        {
            visibility: [0, 1.0],
            type: 'seek',
            frames: [0, 73],
        },
    ]
});
```

**Comment by joeisdead** [comment]
Hi, I tried dropping the 'LottieInteractivity' before and this is the error I ran into:

```
public/pages/lqywa.js: Unexpected token, expected "}" (8:10)

   6 |
   7 | create({
>  8 |     player: '#firstLottie',
     |           ^
   9 |     mode: 'scroll',
  10 |     actions: [
  11 |         {
```

**Comment by joeisdead** [comment]
On the dev toolbar I have two options for where to input my custom code:
<img width="247" alt="Screenshot 2022-03-22 at 10 32 37" src="https://user-images.githubusercontent.com/17277887/159462616-9441b442-8bcf-44d4-bbeb-99e842545328.png">

Should I be using the masterPage.js instead?

**Comment by joeisdead** [comment]
@samuelOsborne I'm afraid I couldn't tell you, my knowledge isn't that strong on the subject. I used the import commands because the site didn't recognise the 'Lottieinteractivity.create'

I do know that Editor X uses [velo by wix](https://www.wix.com/velo) with its own [API](https://www.wix.com/velo/reference/api-overview) for the dev mode stuff. I have been told that Lottie interactivity is supported by both Wix and Editor X.

**Comment by joeisdead** [comment]
@samuelOsborne The Lottie animation on its own plays fine. The trouble I'm having is trying to have it sync on scroll.
I tried the code you sent, here is the error message:
`ReferenceError: Can't find variable: window`

**Comment by samuelOsborne** [comment]
@joeisdead Unfortunately thats a problem on the editor side. Karam also told me that the error you first shared occurs when the JSON can't be loaded correctly, so the editor you're using might be causing problems.

**Comment by joeisdead** [comment]
@samuelOsborne Ah that's unfortunate... I'll try and find another way of animating an svg path on scroll
