### ISSUE TITLE
Animation resets to first frame instead of staying on the last when not looping

### ISSUE THREAD

**Issue by vslavov** [LottieFiles/lottie-player#164]
Demo code:
`        <lottie-vue-player name="test"
                           autoplay
                           :src="'https://assets10.lottiefiles.com/packages/lf20_tzjfwgud.json'" />`
Using 
`
    "@lottiefiles/vue-lottie-player": "^1.0.8",
`
Instead of stopping at the last frame, the animation resets to its first one.

**Comment by samuelOsborne** [comment]
Hi @vslavov, I'll look in to adding this as an option to stay on last frame when not looping.
Cheers.

**Comment by samuelOsborne** [comment]
@vslavov This is fixed with v1.0.9 of the vue-lottie-player.

https://www.npmjs.com/package/@lottiefiles/vue-lottie-player
