### ISSUE TITLE
Can we add variables to the src attribute 

### ISSUE THREAD

**Issue by santosh099** [LottieFiles/lottie-player#169]
How do we add the path to the src attribute to lottie-player in angular from .ts file

**Comment by samuelOsborne** [comment]
Hi @santosh099 

I think you would to it like this:

<lottie-player [src]="your_path" />

your_path being a variable in your component. Im not familiar with angular, I learnt this from here:
https://stackoverflow.com/questions/73320765/passing-props-with-and-without-brackets
