### ISSUE TITLE
Seek using number not working

### ISSUE THREAD

**Issue by venislaus** [LottieFiles/lottie-player#17]
When i use number for seek it is not working, lottie disappears
Only works when i use percentage for seek it works

For example:
Number not works: seek(45)
Percentage works: seek("63%")

I want to use seek using number not by percentage
Please suggest me as i have to make my animation to start playing from specific frame.

**Comment by jawish** [comment]
@venislaus This is now fixed in the 0.3.0 release. Thanks!
