### ISSUE TITLE
Pop glitch pixel in my Lottie animation

### ISSUE THREAD

**Issue by helloblendingmode** [LottieFiles/lottie-player#170]
Hi! I created this animation for Lottie. It has a pop on one of the lines that shows in the Lottie player. Any fixes for this? 
https://lottiefiles.com/share/gtrawpcb

**Comment by samuelOsborne** [comment]
Hi @helloblendingmode I can't reproduce this error and can't see it on chrome, are you using the latest version of the player?

https://codepen.io/Osbro/pen/oNoWGLx
