### ISSUE TITLE
Page crash after HMR

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [LottieFiles/lottie-player#171]
```
This page crashed.
Failed to execute 'define' on 'CustomElementRegistry': the name "lottie-player" has already been used with this registry

Try again
```
![화면 캡처 2022-07-16 115401](https://user-images.githubusercontent.com/78584173/179336568-c7f90eca-85a4-43ed-b2b8-a866fdc7aa4b.png)

I have to reload the page to not get the error.
Happens every time I change code.

**Comment by samuelOsborne** [comment]
@HyunseungLee-Travis This happens when loading the script multiple times on the same page.

**Comment by stephenhebert** [comment]
There are times when it is not possible to avoid running the script multiple times, for instance when two libraries that use the component are used together in the same project.  This is the issue that I am encountering currently.  Would it be possible to check whether the element is already defined before defining it?  This guide has an example: https://medium.com/tuitech/implement-a-ui-library-with-web-components-de0bffcf39ff
