### ISSUE TITLE
Unable to use a imported JSON file as a source.

### ISSUE THREAD

**Issue by AldenB0** [LottieFiles/lottie-player#175]
I am attempting to use a local Bodymovin JSON file instead of a URL within the src=''; however, no method I have currently found to link a file has worked. Is there something on my end that I have missed, or are you unable to link anything other than a URL with the lottie-player.

**Comment by samuelOsborne** [comment]
@AldenB0 Could you please share how you're implementing this?

**Comment by Varunmnx** [comment]
i have also faced the same problem while triying to add a json from lordicons externally downloaded and added to my project but unable to use it in src

**Comment by samuelOsborne** [comment]
@Varunmnx Can you please show any code on how you're implementing

**Comment by cofla159** [comment]
@samuelOsborne hi, I'm facing the same issue and this is how i implemented.
I put the json file in `/src/assets` folder and imported.

![image](https://user-images.githubusercontent.com/70076564/198294186-7cd9e688-b7f6-448f-9aee-a527c597ddc7.png)

**Comment by samuelOsborne** [comment]
Hi @cofla159 

Can you try:

```
<lottie-player
src={JSON.stringify(happyDog)}
...
```

**Comment by cofla159** [comment]
@samuelOsborne wow, It solved directly. I'm kinda ashamed of my stupid, and thanks for your quick response!

**Comment by samuelOsborne** [comment]
Dont be! It's all good @cofla159 . I'll update the docs. Thanks for pointing this out!

**Comment by samuelOsborne** [comment]
I'm going to close this issue as other aren't replying, and stringify will problem solve their problems too.
