### ISSUE TITLE
Callback event when the json run is complete

### ISSUE THREAD

**Issue by josecao** [LottieFiles/lottie-player#18]
Hi author,

let a = document.querySelector('.a');

let url = "string";

a.load(url); 

a.addEventListener('complete', e => {
                console.log('complete');
 });

version : 0.3.0-rc2

it is not work. Pls help me !

**Comment by jawish** [comment]
@josecao If the player is configured to run in loop mode, then there will not be a "complete" event fired. You can use the  "loop" event instead.

```
a.addEventListener('loop', e => {
console.log('loop');
});
```
