### ISSUE TITLE
Latest version is not working

### ISSUE THREAD

**Issue by muhammad-tayyab-tkxel** [LottieFiles/lottie-player#181]
Hey, it seems lottie player [latest version link](https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js) is not wokring. Is there anyone have any knowledge till when it will start working again?

https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js

Showing this:
![image](https://user-images.githubusercontent.com/60883082/198583422-cfdc7be3-0e20-4b1f-9511-15f62dc2d62a.png)

**Comment by samuelOsborne** [comment]
Hi @muhammad-tayyab-tkxel Seems like a problem on unpkg's side. Nothing I can do about that atm, will look in to it to see if its affecting others

**Comment by samuelOsborne** [comment]
@muhammad-tayyab-tkxel If its urgent, you could try using this link:

https://cdnjs.cloudflare.com/ajax/libs/lottie-player/1.6.0/lottie-player.js

**Comment by muhammad-tayyab-tkxel** [comment]
Thanks @samuelOsborne  Yup seems like a problem on unpkg's side. But for now i am going to use version 1.5.7 that is working perfectly fine at that time.

**Comment by muhammad-tayyab-tkxel** [comment]
This has been resolve now.
