### ISSUE TITLE
Bug: JSON files are loaded twice

### ISSUE THREAD

**Issue by bgpedersen** [LottieFiles/lottie-player#184]
Hello,

It seems the json files are loaded twice. 
![image](https://user-images.githubusercontent.com/3582953/205072858-eb2ea28f-b18b-439e-b1fa-b2394a2af64d.png)

It even seems they load twice on your own website:
![image](https://user-images.githubusercontent.com/3582953/205073206-ce8429aa-81c6-4c5c-bac7-a3ee017d65f4.png)

**Comment by samuelOsborne** [comment]
hey @bgpedersen this is on purpose as we do a check on our end to make sure the lottie is valid.

In v1.6.1 you can disable this check by passing the prop 'disableCheck' to the player.

Cheers

**Comment by bgpedersen** [comment]
@samuelOsborne Thanks for the response. I have a question - is this check "only" to verify that the animation works, or does it also check for malicious code/security breaches in the json file? 

The dogs says `Disables verification of the Lottie animation before loading it.`

**Comment by samuelOsborne** [comment]
@bgpedersen Its verify the animation work 👌🏼

yeah if it doesnt work theres a console error
