### ISSUE TITLE
Add support for Canvas as renderer (SVG is buggy on Safari)

### ISSUE THREAD

**Issue by daveaseeman** [LottieFiles/lottie-player#19]
Would be great to build out the renderer property to support canvas. It's the only renderer that works on Safari for a lot of animations.

**Comment by jawish** [comment]
@daveaseeman Checkout the 0.4.0 release. You can now use the canvas renderer using the "renderer" attribute set to "canvas". Thanks

**Comment by daveaseeman** [comment]
Thanks @jawish !

I'm not seeing a bug where the content on my page just starts scrolling up the page by itself... weird one for sure!

Here's my code:
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player
    src="https://assets4.lottiefiles.com/packages/lf20_jCokbl.json"  background="transparent"  speed="1"  style="width: 100%;" **renderer="canvas"** autoplay >
</lottie-player>

**Comment by jawish** [comment]
Try with the latest version (0.5.1) we just released which should have that fixed.

**Comment by daveaseeman** [comment]
Absolutley amazing @jawish - that fixed it and I'm so appreciative that it was pushed so quickly!

**Comment by daveaseeman** [comment]
I'm not able to use the player on our website - so thank you for that!

I'm having one other issue - I'm trying to host our json on a CDN to increase speed because they're big files (~3MB each).

I created a separate issue for this [here](https://github.com/LottieFiles/lottie-player/issues/23).

Do you know what's going on there?

PS let me know if there's a way I can give thansk for your work on this. Would be happy to make a small monetary contribution if this project accepts that.
