### ISSUE TITLE
v1.60 overrides local styles in lottie-player.ts

### ISSUE THREAD

**Issue by tzbarkan** [LottieFiles/lottie-player#195]
We sometimes have multiple Lottie files on a page, which show/hide depending on the breakpoint. We recently had all of those Lottie files show up at once after this line was added to lottie-player.ts:

https://github.com/LottieFiles/lottie-player/blob/6c222e77b3aa32e705f94604eb3539d20d33301a/src/lottie-player.ts#L574

We had to deploy a quick fix with `!important` in our CSS to override this change.

**Comment by samuelOsborne** [comment]
hi @tzbarkan, ive just pushed up v1.7.1 that should fix this
