### ISSUE TITLE
Non looping animation goes back to 1st frame

### ISSUE THREAD

**Issue by foguetes** [LottieFiles/lottie-player#2]
When I disable the looping the animation goes back to the 1st frame instead of pausing at the last one. 

https://jsfiddle.net/Foguete/p6qo5akt/2/

Isn't this a bug?

**Comment by reallynattu** [comment]
@MattDAndre @foguetes it's a bug. we are looking into it. Thanks

**Comment by MattDAndre** [comment]
Thank you! I appreciate that!

**Comment by mlaurita** [comment]
+1

**Comment by hamblyfreeman** [comment]
Any update on this please?

**Comment by jawish** [comment]
The 0.0.7 release should fix the issue.
