### ISSUE TITLE
"parcelRequire is not defined" error when using in Polymer project

### ISSUE THREAD

**Issue by vinhnghi223** [LottieFiles/lottie-player#20]
I did like what being told in the README:
1. `npm install --save @lottiefiles/lottie-player`
2. `import "@lottiefiles/lottie-player";`
3. put these inside my `render()` function
```
<lottie-player
  autoplay
  controls
  loop
  mode="normal"
  src="https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json"
  style="width: 320px"
>
</lottie-player>

```

When I run the build and start local server, I got this error:
```
Uncaught ReferenceError: parcelRequire is not defined
    at parcelRequire.uWh2 (lottie-player.js:1)
    at lottie-player.js:1
```
My component ofcourse never gets rendered.

**Comment by karamalie** [comment]
This issue should be sorted now. New version of the player uses rollup instead of parcel
