### ISSUE TITLE
Minified version of Lottie with bare minimum package size

### ISSUE THREAD

**Issue by harshadsatra** [LottieFiles/lottie-player#204]
Hello Team,

I am using lottie player in Nuxt2 application, Its running great.
I was wandering, if their is any way I can reduce the file size of the Lottie file or Lazy Load it so that it does not affect the loading speed of the application.

**Comment by hermet** [comment]
https://lottiefiles.com/features/optimize-lottie?utm_medium=web&utm_source=navigation-optimize-lottie ?

**Comment by samuelOsborne** [comment]
Hi @harshadsatra , thanks for linking that @hermet. @harshadsatra You can use the Lottie optimizer for a smaller Lottie package size, or use [dotLottie](https://dotlottie.io).

Alternatively, you could fetch and lazy load the .json yourself, and then use the load method of the player and pass the json data directly to the player

**Comment by samuelOsborne** [comment]
Closing this issue out due to inactivity.
