### ISSUE TITLE
Lottie-player l

### ISSUE THREAD

**Issue by Monarc92** [LottieFiles/lottie-player#205]
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player src="https://assets9.lottiefiles.com/packages/lf20_PBgNop.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop controls autoplay></lottie-player>

**Comment by samuelOsborne** [comment]
Hi @Monarc92 What problem are you facing ?

**Comment by ruben44bac** [comment]
The lottie-player.js is down

Your [example](https://lottiefiles.com/web-player) is not working

![Captura de pantalla 2023-04-04 a la(s) 14 02 30](https://user-images.githubusercontent.com/35118058/229907746-252d45fd-b077-4410-a977-4beb7f930ab1.png)

**Comment by samuelOsborne** [comment]
@ruben44bac Is this resolved for you now? Its back online for me.
