### ISSUE TITLE
warning about "Use of eval"

### ISSUE THREAD

**Issue by rjwalters** [LottieFiles/lottie-player#217]
I see the following warning in my build:

> Use of eval in "node_modules/@lottiefiles/lottie-player/dist/lottie-player.esm.js" is strongly discouraged as it poses security risks and may cause issues with minification

Is this something I should be concerned about?

**Comment by fedyk** [comment]
This `eval` seems to be a part of `airbnb/lottie-web` [package](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie_canvas_worker.js#L17306).

At first glance, it looks like legit usage. I'd appreciate it if someone checked this as well.

**Comment by samuelOsborne** [comment]
Hi @fedyk @rjwalters Its part of the lottie-web package.

If you dont want expression support and want to get rid of the warning, please use the [dotlottie-player](https://github.com/dotlottie/player-component) (supports .json and .lottie) with the "light" prop. Cheers!
