### ISSUE TITLE
.animation div adding height to animation

### ISSUE THREAD

**Issue by colderoshay** [LottieFiles/lottie-player#22]
Hey there, after loading my site this morning I noticed the .animation div is now adding variable height to my animation. 

`    .animation {
height: calc(1fr - var(--lottie-player-toolbar-height));}`

You can see it live on the bottom of the hero animation here https://beauzar.com/

**Comment by jawish** [comment]
Hey @colderoshay 

That variable height styling was always there. We have noticed that the latest release does introduce a spacing below the animation and are working on a fix.

You could change the script tag used on your website to reference the older release of the library for an immediate fix.

Change:

```
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
```

to

```
<script src="https://unpkg.com/@lottiefiles/lottie-player@0.3.0-rc2/dist/lottie-player.js"></script>
```

**Comment by colderoshay** [comment]
Thanks a ton @jawish 👍
