### ISSUE TITLE
Controls are not added when disableShadowDOM attribute is present

### ISSUE THREAD

**Issue by tzbarkan** [LottieFiles/lottie-player#233]
With version 2.0.2, if you add the attribute disableShadowDOM, the controls do not render. I do not know if this was present in previous 2.x versions.

Renders controls:
```
<lottie-player autoplay loop controls src="https://lottie.host/4458c0b5-4d8d-43f3-8d42-0739a212a523/L4yrEGvBsO.json"></lottie-player>
```

Just adding disableShadowDom to the above causes them to not be rendered:
```
<lottie-player autoplay loop controls disableShadowDom src="https://lottie.host/4458c0b5-4d8d-43f3-8d42-0739a212a523/L4yrEGvBsO.json"></lottie-player>
```

When inspecting the rendered SVG, `.main` and `.animation` both get the added `controls` className, but `div#lottie-controls` div is not added, nor is any equivalent added.

_Side note:_ using IDs here is going to cause issues if there are multiple lotties on the page.

**Comment by samuelOsborne** [comment]
Hi @tzbarkan This is expected behaviour
