### ISSUE TITLE
Need to update @airbnb/lottie-web dependency version

### ISSUE THREAD

**Issue by alejandroiglesias** [LottieFiles/lottie-player#239]
Animations on our site started looking bad after updating to Chrome v121. We started investigating and we found out that we needed to re-export the animations with the latetst version of the tool our designer uses (Aninix), but also, we needed to update to the latest @airbnb/lottie-web version. I solved it by forking this lottie-player repo and upgrading it there. I can't make a pull request since I had to delete the `@lottiefiles/eslint-plugin` dependency as it is private (see [this issue](#238)) and the lockfile that it would generate would be missing it and break linting. Can you please update the dependency? Also would be a good practice to make `@lottiefiles/eslint-plugin` public so that packages can be installed and pull requests made to this repo.

**Comment by samuelOsborne** [comment]
Hi @alejandroiglesias This player currently uses the most recent version of lottie-web ➡️ 5.12.2
