### ISSUE TITLE
CDN for lottie-player on UNPKG returning 520 error

### ISSUE THREAD

**Issue by thrkll** [LottieFiles/lottie-player#242]
Currently, the lottie-player cdn is returning a 520 error. Animations are thus not loading. 

![image](https://github.com/LottieFiles/lottie-player/assets/48018493/c61f3743-f64f-448c-9fa6-f1cf5a78cc98)

![image](https://github.com/LottieFiles/lottie-player/assets/48018493/eb014c45-8e16-4475-87c8-5cbd71c1939f)

**Comment by theashraf** [comment]
@thrkll

UNPKG is currently down. You might consider switching to Cloudflare CDN instead. https://www.jsdelivr.com/package/npm/@lottiefiles/lottie-player

This change should not impact usage. You can simply replace the UNPKG URL with this one from Cloudflare CDN: https://cdn.jsdelivr.net/npm/@lottiefiles/lottie-player@2.0.4/dist/lottie-player.min.js

**Comment by thrkll** [comment]
Oh that's just great 😂

Thanks a lot @theashraf.
