### ISSUE TITLE
Reverse animation on hover-out?

### ISSUE THREAD

**Issue by Snillsparv** [LottieFiles/lottie-player#25]
I have made an animation and got the code for it through the web-player. I chose it to play on hover and it works perfectly. When the mouse is moved away however it abruptly jumps back to the first frame. Is there any way of having it play the animation in reverse instead (preferably from the current frame)? It would look much more professional.

**Comment by Weslleyjf** [comment]
I have the same problem.

Is there a way to make this?

**Comment by samuelOsborne** [comment]
Hi @Weslleyjf and @Snillsparv if you use the [lottie-interactivity library](https://github.com/LottieFiles/lottie-interactivity) and use the interaction type 'hold' you will achieve this desired interaction. Heres a snippet on how to implement this:

```javascript
  LottieInteractivity.create({
          player:'#thirteenthLottie',
          mode:"cursor",
          actions: [
            {
              type: "hold"
            }
          ]
        });
```
