### ISSUE TITLE
Malicious code in Lottie-Player CDN files

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [LottieFiles/lottie-player#254]
after i use 
`https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js` 
or 
`https://cdn.jsdelivr.net/npm/@lottiefiles/lottie-player@2.0.5/dist/lottie-player.min.js`

This popup opens on my site.

![image](https://github.com/user-attachments/assets/181c972e-3f27-481b-9832-eb8412740baa)

![image](https://github.com/user-attachments/assets/805e243b-c141-48df-9715-f81235c2d3c3)

![image](https://github.com/user-attachments/assets/b83fd8f8-8bbb-40dd-be40-60d68a06b220)

**Comment by cassianogf** [comment]
Up

**Comment by franciscoaguilars** [comment]
Up

**Comment by bnt4** [comment]
Up

**Comment by MrAhmedSayedAli** [comment]
When i open google Dev Tools

![image](https://github.com/user-attachments/assets/20eda40e-4ad7-4556-9c42-3c0fb6f12f39)

**Comment by bnt4** [comment]
You can use Ctrl + F8 to disable breakpoints, then the debugger doesn't "stop" the website.

**Comment by SergejKembel** [comment]
npm versions of this lib got updated few minutes ago https://www.npmjs.com/package/@lottiefiles/lottie-player?activeTab=versions

There is malicious code in last 2 versions. I think the NPM token for deployment was leaked somehow

**Comment by MrAhmedSayedAli** [comment]
> You can use Ctrl + F8 to disable breakpoints, then the debugger doesn't "stop" the website and you can use the dev tools normally.

![image](https://github.com/user-attachments/assets/9fc3d010-82b1-4bc0-91b9-eac0192bb507)
![image](https://github.com/user-attachments/assets/785147f6-ed0e-4817-a7a7-cfe4dc15626c)

**Comment by andres-frank** [comment]
up

**Comment by bnt4** [comment]
npm versions got updated not even one hour ago; https://www.npmjs.com/package/@lottiefiles/lottie-player?activeTab=versions

as @SergejKembel said, virus seems to be in version 2.0.5 and higher.

**Comment by tomoconnor** [comment]
![image](https://github.com/user-attachments/assets/23240b20-0050-469a-bf8e-a65537058372)

**Comment by MrAhmedSayedAli** [comment]
`https://cdnjs.cloudflare.com/ajax/libs/lottie-player/2.0.4/lottie-player.js`  Work Fine For Now

**Comment by edelciomolina** [comment]
Same here!
If you search for 'Ethereum,' you'll see many references to cryptocurrency wallets.
```
https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js
```

I chose to stop using it! Fortunately, we didn’t rely on it much!

**Comment by lukasnobody** [comment]
Just switched to airbnb lib.

Lottiefiles, i'm sorry but you're just like an French TV channel with credentials on the wall)

**Comment by lukasnobody** [comment]
> npm versions got updated not even one hour ago; https://www.npmjs.com/package/@lottiefiles/lottie-player?activeTab=versions
> 
> as @SergejKembel said, virus seems to be in version 2.0.5 and higher.

There is no 2.0.5 or 2.0.6 versions at all. 2.0.4 latest for 8 months, lol...

**Comment by poozipotti** [comment]
+1 here to this, this is the last time it seems the actual code in this repo was updated:
https://github.com/LottieFiles/lottie-player/commit/8b37499efd627e7c622227f5862cb01c124a457b
so 2.0.5 and 2.0.6 have code from ... somewhere?

could this commit also be related? This isn't really my area of expertise but if you look on beta there's a bunch of commits related to the secrets:
https://github.com/LottieFiles/lottie-player/commits/beta

**Comment by bnt4** [comment]
> > npm versions got updated not even one hour ago; https://www.npmjs.com/package/@lottiefiles/lottie-player?activeTab=versions
> > as @SergejKembel said, virus seems to be in version 2.0.5 and higher.
> 
> There is no 2.0.5 or 2.0.6 versions at all. 2.0.4 latest (on github) for 8 months, lol...

Yeah, looks like the virus was directly deployed to npm. Maybe some secret got stolen.

**Comment by zarco-dev** [comment]
![image](https://github.com/user-attachments/assets/f5f06c71-7cfb-421b-be6b-6e712b5d6663)

I have the same error, malware?

**Comment by alejandrotrevi** [comment]
Same here, deleted from my site, never coming back

**Comment by SergejKembel** [comment]
> ![image](https://private-user-images.githubusercontent.com/106997624/381742229-f5f06c71-7cfb-421b-be6b-6e712b5d6663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjM0MDQsIm5iZiI6MTczMDMyMzEwNCwicGF0aCI6Ii8xMDY5OTc2MjQvMzgxNzQyMjI5LWY1ZjA2YzcxLTdjZmItNDIxYi1iZTZiLTZlNzEyYjVkNjY2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2M3NGI3ZjRiY2RkMWRkNTQ2MjliNzZiMzM4NDIxNTFlOTFlZmE4MmRjNTAyYmM0MjE5NGQ1NDA2ODc2YjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xh2fky5aZG6dVwd4B3qFA-jAX1OqBOsk5l10wKWVg3o)
> 
> I have the same error, malware?

No - its a new feature. Please connect your wallet (just kidding - pls dont do that. Yes, its the same issue)

**Comment by canelack** [comment]
I was doing some TryHackMe rooms and they use this library, so this popup showed up 😂
A good reminder that `@latest` versions should be avoided in production to reduce the risk of supply chain attacks.

**Comment by LuisReyes98** [comment]
2.0.4 looks safe for now 
```html
<script src="https://unpkg.com/@lottiefiles/lottie-player@2.0.4/dist/lottie-player.js"></script>
```

**Comment by charif-isl** [comment]
Replace it with a known safe version from a trusted CDN: <script src="https://cdnjs.cloudflare.com/ajax/libs/lottie-player/1.7.1/lottie-player.min.js"></script>

**Comment by zarco-dev** [comment]
For a quick solution, what would be done? just delete these two scripts?

```html
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
```

**Comment by franciscoaguilars** [comment]
> For a quick solution, what would be done? just delete these two scripts?
> 
> ```
> <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
> <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
> ```

You should remove it from your scripts and if you have a package.json also delete it.

**Comment by alancesardasilvasouza** [comment]
![versaolottie](https://github.com/user-attachments/assets/78e0e6cf-9f6c-4be4-9e5b-b4cdcf0b8025)

**Comment by baxtrax** [comment]
To all of those who want to avoid this happening again, setup a CSP (Content Security Policy) so injected scripts like this can't happen. This is typically done in there headers of your website

**Comment by lukasnobody** [comment]
> > ![image](https://private-user-images.githubusercontent.com/106997624/381742229-f5f06c71-7cfb-421b-be6b-6e712b5d6663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjM0MDQsIm5iZiI6MTczMDMyMzEwNCwicGF0aCI6Ii8xMDY5OTc2MjQvMzgxNzQyMjI5LWY1ZjA2YzcxLTdjZmItNDIxYi1iZTZiLTZlNzEyYjVkNjY2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2M3NGI3ZjRiY2RkMWRkNTQ2MjliNzZiMzM4NDIxNTFlOTFlZmE4MmRjNTAyYmM0MjE5NGQ1NDA2ODc2YjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xh2fky5aZG6dVwd4B3qFA-jAX1OqBOsk5l10wKWVg3o)
> > I have the same error, malware?
> 
> No - its a new feature. Please connect your wallet (just kidding - pls dont do that. Yes, its the same issue)

Have connected my wallet, something weird happening with balance. But hope LottieFiles have received this funds and soon will start a tender to buy KeePass,

**Comment by ransome-psl** [comment]
@zarco-dev , if you are using lottie-player would not delete the scripts.  You can modify to a safe version as @LuisReyes98 suggests

`<script src="https://unpkg.com/@lottiefiles/lottie-player@2.0.4/dist/lottie-player.js"></script>`

**Comment by poozipotti** [comment]
It looks like a bunch of changes to the github release workflow happened from Dec. 6 to Jan 10. Wondering if it's the source of the leak?

**Comment by johnfewell** [comment]
> It looks like a bunch of changes to the github release workflow happened from Dec. 6 to Jan 10. Wondering if it's the source of the leak?

Can you post a link to the code you're referring to? A compromised NPM key is the most likely explanation. I think the infected code was pushed pre-complied to NPM.

**Comment by SergejKembel** [comment]
> To all of those who want to avoid this happening again, setup a CSP (Content Security Policy) so injected scripts like this can't happen. This is typically done in the headers of your website

This isn't an injected script if you include it in your HTML header as inline link JS from a CDN like unpkg.

The packagecode itself is infected with, there is no injection.

**Comment by johnfewell** [comment]
Has anyone explored the server that the package tries to make a web socket connect to?

**Comment by tgrassl** [comment]
@SergejKembel A strict CSP would still help with this type of supply chain attack, as the CSP would prevent the injected script from e.g. connecting to unknown external APIs, such as api.web3modal.org in the current lottie-player case

**Comment by PatchRequest** [comment]
> Has anyone explored the server that the package tries to make a web socket connect to?

castleservices01.com points to a cloudflare ip

**Comment by lukasnobody** [comment]
> > Has anyone explored the server that the package tries to make a web socket connect to?
> 
> castleservices01.com points to a cloudflare ip

https://gridinsoft.com/online-virus-scanner/url/zexelon-com

Same address that ICANN gives about castleservices01.com.

**Comment by charif-isl** [comment]
Replace it with a known safe version from a trusted CDN: 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/lottie-player/2.0.4/lottie-player.min.js"></script>`

**Comment by poozipotti** [comment]
Could this code be related? It's very old but may be the culprit. I read through most of these commits and in the beta workflow for the npm jobs a token is echoed out, as well as a github token. Maybe it sat in the workflow logs for a while before someone scraped it or found it somehow? I haven't been able to find the specific deploy where it could have been leaked, but there are a few deleted logs in the deployment history on the repo. I'm not really a devops expert so I don't know what is typical here.

My best guess is there was a bunch going wrong with the npm job and the only way to test it was by deploying, and somewhere along the line a token got leaked. Someone with more experience in github workflows could probably find out for certain though. 

**main branch**

c098e7c samuelOsborne   Tue Jan 10 09:58:40 2023 +0100  fix: added release workflow
300d13a samuelOsborne   Tue Jan 10 09:51:57 2023 +0100  fix: added release workflow
4aa05a3 samuelOsborne   Wed Dec 7 11:11:56 2022 +0100   chore: removed relase file
0581409 samuelOsborne   Tue Dec 6 15:32:50 2022 +0100   feat: added getVersions, updated lottie-web, updated release workflow

**beta branch**

c986799 samuelOsborne   Tue Jan 10 15:17:06 2023 +0100  fix: npm job install fix
5181e20 samuelOsborne   Tue Jan 10 14:57:39 2023 +0100  fix: npm job install fix
639e4eb samuelOsborne   Tue Jan 10 14:51:36 2023 +0100  fix: npm job install fix
e00fd44 samuelOsborne   Tue Jan 10 14:29:37 2023 +0100  fix: npm job install fix
60b19e4 samuelOsborne   Tue Jan 10 14:16:56 2023 +0100  fix: npm job install fix
1a4d4b2 samuelOsborne   Tue Jan 10 14:06:18 2023 +0100  fix: npm job install fix
d024272 samuelOsborne   Tue Jan 10 13:55:54 2023 +0100  fix: npm job install fix
3b22f8b samuelOsborne   Tue Jan 10 10:58:22 2023 +0100  fix: npm job install fix
8d3ca96 samuelOsborne   Tue Jan 10 10:46:32 2023 +0100  fix: npm job install fix
c098e7c samuelOsborne   Tue Jan 10 09:58:40 2023 +0100  fix: added release workflow
300d13a samuelOsborne   Tue Jan 10 09:51:57 2023 +0100  fix: added release workflow
4aa05a3 samuelOsborne   Wed Dec 7 11:11:56 2022 +0100   chore: removed relase file
0581409 samuelOsborne   Tue Dec 6 15:32:50 2022 +0100   feat: added getVersions, updated lottie-web, updated release workflow

**Comment by LiorLindvor** [comment]
<img width="810" alt="image" src="https://github.com/user-attachments/assets/a438ba70-0811-4718-99da-3a28f1c29b8e">

@aidosmf your token might be exposed...

**Comment by nyxs** [comment]
![image](https://github.com/user-attachments/assets/3f6f25d7-599a-466d-8c0e-da33b55d978e)

Version 2.0.7 is on its way

**Comment by lukasnobody** [comment]
![image](https://github.com/user-attachments/assets/8ef1a63a-4074-44b1-8975-efd13d7bbb70)

**Comment by tgrassl** [comment]
Beware, 2.0.7 still contains the malicious code

**Comment by lukasnobody** [comment]
> Beware, 2.0.7 still contains the malicious code

For real?

**Comment by SergejKembel** [comment]
> ![image](https://private-user-images.githubusercontent.com/20337331/381753523-3f6f25d7-599a-466d-8c0e-da33b55d978e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjYxMjIsIm5iZiI6MTczMDMyNTgyMiwicGF0aCI6Ii8yMDMzNzMzMS8zODE3NTM1MjMtM2Y2ZjI1ZDctNTk5YS00NjZkLThjMGUtZGEzM2I1NWQ5NzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIyMDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzE1ZTQ4ODk0MDIwOWQ5MDdhNjliNmMwMTYxYTZhYWE3YzE5OWZmZDdjOWIyMDUwY2Q2OTIwNTkzMjljMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hwNHF6W4C7gqwH1Z_msqkx0Oi7IJLt9xgbVseVyP38g)
> 
> Version 2.0.7 is on its way

Probably still infected - wouldn't use it for now.

**Comment by tgrassl** [comment]
@lukasnobody Yes, you can check the uploaded code in e.g. dist/lottie-player.js or here https://www.npmjs.com/package/@lottiefiles/lottie-player/v/2.0.7?activeTab=code

**Comment by bplv112** [comment]
Looks like all the version after 2.0.1 is malicious, which makes sense as github only shows release till 2.0.1, all the other releases looks corrupt.

**Comment by SergejKembel** [comment]
![image](https://github.com/user-attachments/assets/11596ed0-3f23-42c8-aee4-6a2cf3d42c6d)
![image](https://github.com/user-attachments/assets/0f8e6721-b638-43ad-a6fc-72c5caeec6f0)

2.0.4 is 6.9MB and 2.0.7 is 9.74MB - nothing was fixed since 2.0.5, but rather URLs were adjusted

**Comment by lukasnobody** [comment]
> @lukasnobody Yes, you can check the uploaded code in e.g. dist/lottie-player.js or here https://www.npmjs.com/package/@lottiefiles/lottie-player/v/2.0.7?activeTab=code

Sergej posted above. Can be easily determined by "Unpacked size". Infected size much bigger.

**Comment by johnfewell** [comment]
Are the hackers lurking this thread?

**Comment by SergejKembel** [comment]
> Looks like all the version after 2.0.1 is malicious, which makes sense as github only shows release till 2.0.1, all the other releases looks corrupt.

https://github.com/LottieFiles/lottie-player/commit/8b37499efd627e7c622227f5862cb01c124a457b

2.0.4 is a commit on master

**Comment by bplv112** [comment]
Oh looks like I stand corrected. 2.0.4 is the most recent safe version. 
It is weird that it was never released on github though.

**Comment by PatchRequest** [comment]
> Are the hackers lurking this thread?

We are already on twitter :)
https://x.com/CerastIntel/status/1851729392256311611

**Comment by jawish** [comment]
Thanks for reporting this! We are tackling this now.

**Comment by Y8765** [comment]
For the other guys mentioned how to deal with script that has been changed, you need to use SRI with file hash, then even if script jut hijacked/injected, when you load it into your site, the hash wouldn't match and will drop the file from loading.

**Comment by bronthulke** [comment]
> For the other guys mentioned how to deal with script that has been changed, you need to use SRI with file hash, then even if script got hijacked/injected, when you load it into your site, the hash wouldn't match and will drop the file from loading.

That won't help if you are using the "latest" version, though, right?

**Comment by quarryman** [comment]
> > For the other guys mentioned how to deal with script that has been changed, you need to use SRI with file hash, then even if script got hijacked/injected, when you load it into your site, the hash wouldn't match and will drop the file from loading.
> 
> That won't help if you are using the "latest" version, though, right?

You can not use latest version with SRI

**Comment by nyxs** [comment]
I can conclude so far that:
1. The code under "lottie-player.js" targets "app.1inch[.]io" website.
2. Its primary goal is to connect to the user's crypto wallet
3. It adds new blockchain networks to the wallet
4. It enables interaction with smart contracts.

It doesn't seem like the code sends money directly somewhere, but there is ABI encoding logic there.

Continue investigating.

**Comment by gexly** [comment]
> > For the other guys mentioned how to deal with script that has been changed, you need to use SRI with file hash, then even if script got hijacked/injected, when you load it into your site, the hash wouldn't match and will drop the file from loading.
> 
> That won't help if you are using the "latest" version, though, right?

Latest version (2.0.5) from: https://cdnjs.com/libraries/lottie-player has SRI, but also malicious.

**Comment by mason-rogers** [comment]
I'd like to drop in and say that I've personally been receiving some phishing emails from fake npm domains, as well as all of our staff members - and it's possible that's what happened here. I didn't click any links and so I'm not sure exactly what it does

<img width="622" alt="image" src="https://github.com/user-attachments/assets/09fc09b6-82c4-491d-a63b-b3e301e0710c">

**Comment by nyxs** [comment]
Who is "aidosmf <aidosmf@gmail.com>"?
@mason-rogers Do you know him?
I saw it once in the npm info and his gone.

**Comment by mason-rogers** [comment]
@nyxs https://github.com/aidosmf

**Comment by quarryman** [comment]
> > > For the other guys mentioned how to deal with script that has been changed, you need to use SRI with file hash, then even if script got hijacked/injected, when you load it into your site, the hash wouldn't match and will drop the file from loading.
> > 
> > 
> > That won't help if you are using the "latest" version, though, right?
> 
> Latest version (2.0.5) from: https://cdnjs.com/libraries/lottie-player has SRI, but also malicious.

You should have control over integrity hash on your side for it to work

**Comment by nyxs** [comment]
> @nyxs https://github.com/aidosmf

Yeah, but is he one of the owners here?
I mistakenly tagged you instead of @jawish

**Comment by nyxs** [comment]
2.0.7 is deprecated now, I guess it's @jawish 
![image](https://github.com/user-attachments/assets/2847afb8-0f91-463b-98a9-454a65715985)

**Comment by mason-rogers** [comment]
> > @nyxs https://github.com/aidosmf
> 
> Yeah, but is he one of the owners here? I mistakenly tagged you instead of @jawish

Nw - yeah he appears to be, he's in the LottieFiles org

**Comment by jawish** [comment]
We are still investigating but it seems like, as you folks have identified, @Aidosmf token was compromised.

The token was used to publish versions 2.0.5, 2.0.6, 2.0.7 in succession releases over 3 hours.

2.0.5 - pushed to npm at 8:12 PM GMT, 30 Oct 2024
2.0.6 - pushed to npm at 8:35 PM GMT, 30 Oct 2024
2.0.7 - pushed to npm at 9:57 PM GMT, 30 Oct 2024

We have removed the compromised account access and published a new 2.0.8 version that is a copy of the 2.0.4, for all those of you who are using the implicit latest tag via CDNs.

If you are using it by explicitly specifying the version and are using any of the affected versions, please change to 2.0.4 or 2.0.8. We have reached out to npm to help unpublish the affected versions as their web portal and CLI is not letting us unpublish the affected versions.

**Comment by teamgroove** [comment]
And what about the cdns? As long as they serve them, this is still a pandorras-box for eternity?
The crap should be deleted and overwritten with a blank file or redirected to a valid one. It breaks the integrity, of course. 
Does our cdn-industry already have a solution to this in the semver-world they exisit in?

**Comment by teamgroove** [comment]
I realized i never thought about it, but the cdns then have a historicall trackrecord of every malware-breach. You can always go back and study malware, right?! Or reinfect. Hm.

**Comment by jkobus** [comment]
I created a copy of it for scientific purposes for anyone interested here:
https://gist.github.com/jkobus/57f7a198c521237d980753d9025893b8

**Comment by jawish** [comment]
**UPDATE:**

The affected versions have now been removed from npmjs.com (2.0.5, 2.0.6, 2.0.7).

If you had once of these versions explicitly specified in package.json, please do bump to 2.0.8.

The new 2.0.8 release is being served on CDNs as the latest, that should fix the issue for many folks (but highly recommend using a fixed version as best practice). The compromised versions have been automatically removed from jsDeliver but not CDNjs.com so they are, currently, still accessible if accessed via the explicit version specifier.

**Comment by Abistal22** [comment]
Hey, i was working in localhost with the one of the compromised cdns included in script tag. I clicked "X" each time the same modal popped up and didn't click on any of the other options it gave me. I am new dev and this is the first time something like this happened to me. Should i check for malware even though i haven't clicked on any of the links they provided and haven't given any sensitive information and is my pc at risk? Thank in advance.

**Comment by NagliNagli** [comment]
I've put up a Twitter recap and also Nuclei Template Detection for the specific versions above ^ 

https://x.com/galnagli/status/1851779972639363076

Template:

https://gist.github.com/NagliNagli/be5f4cb8be90a3c3985ef776b1b3dd73

**Comment by reallynattu** [comment]
### Incident Response for Recently Infected Lottie Web Player versions 2.05, 2.06, 2.07

**Comm Date/Time:** Oct 31st, 2024 04:00 AM UTC 

**Incident:** On October 30th ~6:20 PM UTC - LottieFiles were notified that our popular open source npm package for the web player @lottiefiles/lottie-player had unauthorized new versions pushed with malicious code. This does not impact our dotlottie player and/or SaaS services. Our incident response plans were activated as a result. We apologize for this inconvenience and are committed to ensuring safety and security of our users, customers, their end-users, developers, and our employees. 

**Immediate Mitigation Actions**
- Published a new safe version (2.0.8) 
- Unpublished the compromised package versions from npm 
- Removed all access and associated tokens/services accounts of the impacted developer

**Impact**
- Versions 2.0.5, 2.0.6, 2.0.7 were published directly to npmjs.com over the course of an hour using a compromised access token from a developer with the required privileges. 
- The unauthorized versions contained code that prompted for connecting to user’s crypto wallets. 
- A large number of users using the library via third-party CDNs without a pinned version were automatically served the compromised version as the latest release. With the publishing of the safe version, those users would have automatically received the fix. 

**Recommended Steps**
- If using 2.0.5, 2.0.6 and 2.07 versions please update to the latest version 2.0.8
SHA: sha512-PWfm8AFyrijfnvGc2pdu6avIrnC7UAjvvHqURNk0DS748/ilxRmYXGYkgdU1z/BIl3fbHCZJ89Zqjwg/9cx6NQ==
- If you are unable to update the player immediately, it is recommended that you communicate to Lottie-player end-users to NOT accept any attempts to connect their crypto wallets. 

**Next Steps** 
- LottieFiles continues to work through its incident response plan and has also engaged an external incident response team to help further investigate the compromise. 
- We have confirmed that our other open source libraries, open source code, Github repositories, and our SaaS were not affected.

If you believe you’re affected, don’t hesitate to reach out to us at priority_support@lottiefiles.com

**Comment by feliperodriguess** [comment]
@jawish @reallynattu  Hey guys! Asking just in case: 

Is everything good w/ `@lottiefiles/react-lottie-player` (version `^3.5.4`)? Has this package been affected by any means?

**Comment by xmflsct** [comment]
> **UPDATE:**
> 
> The affected versions have now been removed from npmjs.com (2.0.5, 2.0.6, 2.0.7).
> 
> If you had once of these versions explicitly specified in package.json, please do bump to 2.0.8.
> 
> The new 2.0.8 release is being served on CDNs as the latest, that should fix the issue for many folks (but highly recommend using a fixed version as best practice). The compromised versions have been automatically removed from jsDeliver but not CDNjs.com so they are, currently, still accessible if accessed via the explicit version specifier.

Quick update for whoever is watching this issue. CDNJS now redirects the affected versions to `2.0.8`.
