### ISSUE TITLE
Lottie Player hacked?

### ISSUE THREAD

**Issue by johnfewell** [LottieFiles/lottie-player#255]
A new version was published to NPM 15 minutes ago, now a Crypto wallet popup is showing which is launched by Lottie Player:
![image](https://github.com/user-attachments/assets/0e544e89-12bc-41df-9469-a40c38255031)

![image](https://github.com/user-attachments/assets/3488e14f-af76-4b57-88e7-a64d95b9d6b1)

Please advise.

**Comment by bradsobie** [comment]
same

**Comment by SidiBecker** [comment]
Yes!!!!

**Comment by MrAhmedSayedAli** [comment]
same #254

**Comment by bnt4** [comment]
Use version 2.0.4

**Comment by mivios** [comment]
they screw up... the version 2.0.6 have this problem, downgrade to 2.0.0

**Comment by johnfewell** [comment]
> Use version 2.0.4

Yes, that's what we are doing. Getting that fix to prod is the problem.

**Comment by johnfewell** [comment]
Dupe of https://github.com/LottieFiles/lottie-player/issues/254
