### ISSUE TITLE
Multiple lottie file using js

### ISSUE THREAD

**Issue by ghost** [LottieFiles/lottie-player#28]
in the documentation it says we can initialize lottie file in js: 

```
const player = document.querySelector("lottie-player");
player.load("https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json");
```

but when if I have multiple lottie files?

```js
var player = $('.lottie-icon');
player.load(...);
```

```html
<lottie-player class="lottie-icon" background="transparent"  speed="1"  style="width: 300px; height: 300px;"    ></lottie-player>
```

is not working

**Comment by daniel-ilan** [comment]
I don't think this player or the original bodymovin player has this capability. You have to load multiple lottie-player elements, if you get the files from the server then just use a loop in the code and generate the players dynamically

**Comment by karamalie** [comment]
@daniel-ilan is correct. you'd need multiple instances of the player to load multiple Lotties. to use the same instance of the player. you would need to call the .destroy() method first before loading up the next animation via .load()
