### ISSUE TITLE
Lottie-player on scroll

### ISSUE THREAD

**Issue by antnoyce** [LottieFiles/lottie-player#3]
New to JS so this maybe really simple / above my knowledge so appologies, but i have a WP site and i am playing a sample .json via lottie-player. Currently set to autoplay & loop, and working ok.

http://anthonynoyce.design/verbose/test-animation/

I want to scrub through the frames as i scroll down the page, but i cant easily understand how the scroll example is working https://ypxk7zvpq1.codesandbox.io/. Tried to copy the script in the source:

<script>
const elems = document.querySelectorAll('lottie-player');
function getOffsetPercent(el) {
const rect = el.getBoundingClientRect();
const yDiff = Math.abs((window.innerHeight / 2) - (rect.top + rect.height / 2));
const yPercent = Math.min(1, Math.max(0, (rect.height - yDiff) / rect.height));
return Math.round(yPercent * 100);
}
function scrub() {
elems.forEach(el => {
const container = (el.dataset.container)
? document.querySelector(el.dataset.container)
: el;
el.seek(`${getOffsetPercent(container)}%`)
});
}
  
window.addEventListener('scroll', function(event) {
scrub();
});
</script>

but i can get it to work, can any one point me in the right direction / resources.

**Comment by jawish** [comment]
@antnoyce You don't seem to have the lottie-player script tag in the head of the document. Please add the following between the `head` tag.

```
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
```

**Comment by antnoyce** [comment]
Hey Jawish,
Thanks for looking, i did get this to working in the end with the bodymovin player, couldnt get the above hooked up with the lottie player above

**Comment by jawish** [comment]
Fantastic.
