### ISSUE TITLE
Please use rollup to bundle lottie-player instead of parcel

### ISSUE THREAD

**Issue by lovetingyuan** [LottieFiles/lottie-player#35]
`rollup`  is a better choice for library bundle, while `parcel` is more suitable for application development.
For example, output bundle by `parcel` can not be used as es-module directlly.

**Comment by lovetingyuan** [comment]
here is a similar issue: https://github.com/LottieFiles/lottie-player/issues/20

**Comment by johnloy** [comment]
It's also worth shipping the source ES modules unbundled as well to npm. I notice Lottie Player uses LitElement, and not bundling that is ideal, so it can be externalized and shared in production builds among other custom elements depending on it.

**Comment by lozandier** [comment]
I'm having issues importing the component in projects using npm because `parcelRequire` ; it seems related to this.

**Comment by abinoda** [comment]
Same here

**Comment by karamalie** [comment]
changed build process from parcel to rollup :) v1.0.0 has been pushed out
