### ISSUE TITLE
What's the recommended way to create a playlist of files?

### ISSUE THREAD

**Issue by adrianknight89** [LottieFiles/lottie-player#4]
I'd like to play multiple files back to back and reset back to the beginning to create an auto loop. How do you recommend we do this? Looking at your documentation under Methods, I did not see a setSource() method. It'd also be great to have a property of lottie-player (srcList, items, or something similar) to define a list of json files to be played.

**Comment by jawish** [comment]
We have just pushed a release with a method exposed for loading animations. That was a miss on our part, thanks for bringing it to our attention!

I've setup a quick demo of how you could have a loop of multiple Lottie animations playing using the new method for loading animations.

[https://codesandbox.io/s/play-a-list-of-lottie-animations-in-a-sequence-un58i](https://codesandbox.io/s/play-a-list-of-lottie-animations-in-a-sequence-un58i)

Hopefully this gets you pointed in the right direction?

**Comment by adrianknight89** [comment]
Just looked at the demo. It looks good. One quick question. Is there a way to load all three animations before playing them? I believe `playNext()` changes the source file which then needs to be fetched. It'd be great to download everything ahead of time to reduce any network lag. 

Does `src` only accept a json file or can I supply the content of the file itself? If it's the latter, then I can download the files before setting up the player and send file content in the `load()` function when animating the playlist.

**Comment by jawish** [comment]
Yep that would work! Just specify the JSON inline in the animations array or tweak the code to preload the data (or even warm the browser cache with a fetch). The player takes JSON string/object or URL so your suggested approach will work just fine.

**Comment by adrianknight89** [comment]
Great. Thank you again!
