### ISSUE TITLE
Direction doesn't work as attribute

### ISSUE THREAD

**Issue by daledesilva** [LottieFiles/lottie-player#40]
The direction attributes is listed to take a number, defaulting to 1.
Passing in any other number, however, when editing the script tag manually, doesn't do anything.

In the Web Players page, the direction dropdown gives the option of forward or backward and appears to work, however...
1. It doesn't change the script snippet - so it doesn't work when copied and pasted.
2. Looping ceases working.

https://lottiefiles.com/web-player

**Comment by Pocket-titan** [comment]
Looking at the code, the values appear to be `1` for forward and `-1` for backward. But it might indeed be nice to document this somewhere :)

**Comment by karamalie** [comment]
updated docs with the value hint
