### ISSUE TITLE
White background around seek Bar of lottie player in Firefox

### ISSUE THREAD

**Issue by Aravinth07** [LottieFiles/lottie-player#41]
![image](https://user-images.githubusercontent.com/68121264/94507446-9fbb4480-01c4-11eb-8bf2-1425ae817dae.png)
![image](https://user-images.githubusercontent.com/68121264/94507523-ca0d0200-01c4-11eb-90c9-410c1a24b12f.png)
I used the <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
while I inspecting I found background of .seeker class is white and I changed to transparent by getting lottie-player.js in my local  and its working fine now.
![image](https://user-images.githubusercontent.com/68121264/94508200-4a803280-01c6-11eb-9857-9ce83fb709b8.png)

**Comment by samuelOsborne** [comment]
Fixed with latest version of lottie-player.
