### ISSUE TITLE
Give us events to know when animation started and ended

### ISSUE THREAD

**Issue by adrianknight89** [LottieFiles/lottie-player#5]
It'd be nice to know when an animation starts playing and when it ends so that we can apply custom logic in the UI. Ideally, there should also be a way to know if the animation failed to load.

**Comment by jawish** [comment]
Just cut a release with events exposed.

| Event | Description |
| ------ | -------------|
| load | Animation data is loaded.
| error | An animation source cannot be parsed or fails to load.
| ready | Animation data is loaded and player is ready.
| play | Animation starts playing.
| pause | Animation is paused.
| stop | Animation is stopped.
| freeze | Animation is paused.
| loop | An animation loop is completed.
| complete | Animation is complete (all loops completed).
| frame | A new frame is entered.

You can listen to events using the `addEventListener` call as usual. For e.g.:
```js
const player = document.querySelector('lottie-player');
player.addEventListener('load', e => {
    console.log('load');
});
player.addEventListener('ready', e => {
    console.log('ready');
});
player.addEventListener('error', e => {
    console.log('error');
});
```

Is that helpful?

**Comment by adrianknight89** [comment]
This is great. Thanks! What's the difference between `pause` and `freeze` since the documentation on both is the same. It'd be beneficial to make the difference more clear in the documentation.

**Comment by jawish** [comment]
Great point. `freeze` is when the player is paused when the tab/window is not active or when the player is out of the view in the current window. It really is an internal state that pauses animation and is used to differentiate between user requested pauses and component instigated pauses.

**Comment by adrianknight89** [comment]
Thank you!!
