### ISSUE TITLE
How it be used in angular ?

### ISSUE THREAD

**Issue by qqaimh** [LottieFiles/lottie-player#7]
How it be used in angular ? Thanks

lottie-player.js:1 Uncaught ReferenceError: parcelRequire is not defined
    at push../node_modules/@lottiefiles/lottie-player/dist/lottie-player.js.parcelRequire.uWh2 (lottie-player.js:1)
    at Object../node_modules/@lottiefiles/lottie-player/dist/lottie-player.js (lottie-player.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.component.ts (main.js:143)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.component.ts:10)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (main.ts:12)

**Comment by sean-perkins** [comment]
This appears to be an issue with using a component compiled with Parcel in a webpack environment. 

To get around this, my team has created a clone of this project using StencilJS instead of lit-element. 

https://github.com/TeamHive/lottie-player

Simply install the component:
```shell
npm install --save @teamhive/lottie-player
```

Register the element in your `main.ts`

```ts
import { defineCustomElements } from '@teamhive/lottie-player/loader';

defineCustomElements(window);
```

And use the same mark-up, attributes, etc. as described in this repository.

**Comment by anewtonlevey** [comment]
For anyone else, I was able to get it working by installing via npm then

Importing into the module and setting CUSTOM_ELEMENTS_SCHEMA

`import { LottiePlayer } from '@lottiefiles/lottie-player';`

````
@NgModule({
    declarations: [LoadingSpinnerComponent],
    imports: [CommonModule, MatProgressSpinnerModule, OverlayModule],
    exports: [LoadingSpinnerComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA], // Needed for Lottie Player
})
export class LoadingSpinnerModule {
    private ref = LottiePlayer; // Get a reference so it doesn't get tree shaken out
}
````


And in the component HTML
`<lottie-player
        autoplay
        loop
        mode="normal"
        src="/assets/loading.json"
        style="width: 100px"
    ></lottie-player>`

**Comment by karamalie** [comment]
The player is no longer being compiled with parcel. We ve switched to rollup. For those of you using the earlier players or are getting the same issue still, do follow the solution @anewtonlevey provided. Closing this issue.
