### ISSUE TITLE
Possibility of choosing render mechanism

### ISSUE THREAD

**Issue by knenkne** [LottieFiles/lottie-player#78]
Currently there is SVG renderer, but it would be great to have choice and face crossplatform bugs on early stage, thx

**Comment by karamalie** [comment]
svg renderer and canvas renderer both are available. the property 'renderer'  can be passed in with a string option

**Comment by knenkne** [comment]
Thank u, but still, how can I edit it right in the lottie web player? There it no such a controls and textfield is not editable, i dont want to create my own an enviroment to make sure that everthing is all right
![image](https://user-images.githubusercontent.com/35743791/122883351-c8ccc800-d345-11eb-9349-93ad4ec9677f.png)

**Comment by karamalie** [comment]
<lottie-player src="https://assets5.lottiefiles.com/datafiles/zc3XRzudyWE36ZBJr7PIkkqq0PFIrIBgp4ojqShI/newAnimation.json"  background="transparent" renderer="canvas" speed="1"  style="width: 300px; height: 300px;"  loop controls autoplay></lottie-player>

**Comment by knenkne** [comment]
Thanks, i understand how it works. I mean is it possible to do exactly at [LottieFiles](https://lottiefiles.com/ ) preview section without creating own enviroment. Our designers create crossplatform animations, so we want them to check animations themselves before developing, so my goal is to have such possibility just after uploading animation to service. I want to point out once again that textfield with generated code is not editable

**Comment by knenkne** [comment]
It's not a problem exactly of web-player, it's a feature request for LottieFiles service

**Comment by karamalie** [comment]
@knenkne ive passed on the feedback to the LottieFiles web team :)

**Comment by knenkne** [comment]
Big thanks
