### ISSUE TITLE
Uncaught TypeError: this.container is null

### ISSUE THREAD

**Issue by slushpuppy** [LottieFiles/lottie-player#79]
Problem: There appears to be a race condition when dynamically adding lottie-player to dom then performing a load() soon after

https://jsfiddle.net/p2n8hjq7/

Solution: Could we have some sort of event that only fires load() after lottie engine has been initialized for the newly added element?

**Comment by karamalie** [comment]
added an event dispatch for onrender. Please update to latest version 1.0.5 and attempt as shown below

![Screenshot 2021-06-22 at 11 51 18 AM](https://user-images.githubusercontent.com/12868819/122860754-dd628d80-d350-11eb-891e-abf6f1e4324e.png)
