### ISSUE TITLE
Animation Exporting not full animation

### ISSUE THREAD

**Issue by Akrasnovskis** [LottieFiles/lottie-player#80]
Hi There, 

I do have an issue when trying to export animation. So I use an extension in AF and when that loads that animation and when exporting, animation or not full or behave very different from original animation and not sure why is doing it? URL to the animation below, if someone could direct me if I missing anything or doing incorrect things.

Highly appreciate your help in advance

https://www.dropbox.com/s/130d7vwucege6bq/project.aep?dl=0

**Comment by karamalie** [comment]
Hi this seems to be an issue thats related with how you create the animation in After Effects. I would suggest asking this question on the Lottie community at discord [https://lottiefiles.com/discord](https://lottiefiles.com/discord)
