### ISSUE TITLE
Lootiefile player not working in all my website with v1.0.0

### ISSUE THREAD

**Issue by cesaracostamtz** [LottieFiles/lottie-player#82]
This new version 1.0.0 of lootiefile player is not loading for all my website. Please review why is not working, I think we are not the only ones with this issue.
My site: https://lazzo.io

**Comment by karamalie** [comment]
Updated player to v1.0.6 along with the fix. Please check now

**Comment by karamalie** [comment]
#83 https://github.com/LottieFiles/lottie-player/issues/83
