### ISSUE TITLE
Animation are not showing after v1

### ISSUE THREAD

**Issue by RaulRueda** [LottieFiles/lottie-player#83]
I think is because the last release and we are importing last version via CDN `<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>`

Switching back to v0.1.0 fix most of them

JSFiddle example
![image](https://user-images.githubusercontent.com/26230166/122876836-9302f180-d2fb-11eb-9537-72566979bc61.png)

**Comment by karamalie** [comment]
Hi @RaulRueda please double confirm for me with v1.0.6. pushed out an update

<script src="https://unpkg.com/@lottiefiles/lottie-player@1.0.6/dist/lottie-player.js"></script>

**Comment by RaulRueda** [comment]
> Hi @RaulRueda please double confirm for me with v1.0.6. pushed out an update
> 
> <script src="https://unpkg.com/@lottiefiles/lottie-player@1.0.6/dist/lottie-player.js"></script>

Now is working, thanks @karamalie
