### ISSUE TITLE
Feature request: show the first frame of lottie then animate on hover

### ISSUE THREAD

**Issue by RezaRahmati** [LottieFiles/lottie-player#85]
In my page I want to show the icon and when use hover on it, then it starts animating,

I tried to `hover`, but it doesn't show anything unless you hover on that area.

Is there anyway to achieve that? if not would you please consider it as a feature request?

**Comment by FreshImmuc** [comment]
Yes. Please. And also an option to "toggle" it. FIrst click: play animation from 1% to 99% and second click: play animation from 99% to 1%. Also the option to add custom css easings.

**Comment by karamalie** [comment]
We are working on expanding our interactivity library that works together with the player. Once that is completed, the chaining of different interactions should be easier in the future :) @FreshImmuc 

@RezaRahmati . you could call player.getLottie().goToAndStop() method and move the static frame to your desired frame number and then add some custom javascript to listen for hover and call the play() method. in the same way listen for hover out and stop the lottie using player.getLottie().goToAndStop()

**Comment by samuelOsborne** [comment]
Closing as this can be achieved by having a visible first frame and playing on hover.
