### ISSUE TITLE
playSegment/get current frame in lottie-player

### ISSUE THREAD

**Issue by pinoybai** [LottieFiles/lottie-player#88]
Hi,

I would like pause the player at a certain frame on play. but playSegment is not supported by lottie-player. 

so I tried using 'frame' event to determine the current frame and pause at certain frame. but this event doesn't provide the current frame entered data. 

I used a variable and incremented every time a new frame is entered with the 'frame' event. But the increment is not accurate (changes every time). 

Below is my code:

```      
$('#wrapper lottie-player').each(function(){
		      let lottie_frame = 0;
		      let the_id = $(this).attr('id');
		      let end_frame = parseInt(document.getElementById(the_id).getAttribute('data-end_frame'));
		
		document.getElementById(the_id).addEventListener('frame', function(e){
			lottie_frame++;
			if(parseInt(lottie_frame) == end_frame){
				document.getElementById(the_id).pause();
				lottie_frame = 0;
			}
		});
});
```

Could you please let me know how to play the player with segments? if not possible may I know how to get the accurate current frame?

Note: I can only use `<lottie-player>` not the other bodymovin load animation script.

Regards,

**Comment by karamalie** [comment]
Hi @pinoybai ,
As this library is a web component wrapper around the main lottie renderer engine, 
you can access the lottie instance by 
1 - var player = document.getElementById() to grab the player
2 - call the var lottie = player.getLottie() method 
3 - use the returned instance from getLottie() and call the playsegments. lottie.playSegments([10,10],true)

with that in mind. once you get the instance using the getLottie() method. the object will contain an updated frame value that is accurate too. hope that helps!

**Comment by pinoybai** [comment]
It does! Thank you!
