### ISSUE TITLE
Feature request : Progressive Load

### ISSUE THREAD

**Issue by Ploonet** [LottieFiles/lottie-player#89]
Hi,

This lottie-player seems to be missing a feature that would help with loading larger animations : [lottie-web](https://github.com/airbnb/lottie-web) the "progressiveLoad" true/false property.
I'm sure this would reduce Total Blocking Time by a lot for some websites.

The feature could be enabled/disabled in the same way that we currently toggle the controls, autoplay, etc.

**Comment by karamalie** [comment]
Hi @Ploonet 
We ve not exposed it as a prop as we have set progressive load to true as a default [here](https://github.com/LottieFiles/lottie-player/blob/08e991f0a4a584f2da46ae5cdf00384c980cfd17/src/lottie-player.ts#L246) . Would it be useful for you to be able to toggle it off? It can be exposed if needed
