### ISSUE TITLE
My lottie website stopped working

### ISSUE THREAD

**Issue by Dazag** [LottieFiles/lottie-player#95]
We still don't know why, but the last version you deployed yesterday (1.1.2), caused my website to stop using the animations. It seems like it can't obtain the path to the animation images. Version 1.1.1 works just fine. The error specified that the images didn't existe, because it was trying to obtain them from a wrong path.

**Comment by karamalie** [comment]
will push up a fix soon. Thank you!

**Comment by Dazag** [comment]
Sorry I didn't answer before, can't publish any information since I am working for someone else in this matter. I'm sorry for that too. The only thing we did was to use the latest and suddenly it stopped locating them in the server because of a wrong path being generated. It was working fine just before the last version (I mean finding the assets)

**Comment by karamalie** [comment]
should be working now. we ve reverted the changes on that version. Is it still not working?

**Comment by Dazag** [comment]
I changed my assets to point to the previous version and it began to work normally. I will test the new changes and let you know, thank you so much!
